/*
 * Generated by Resin 2.1.8 (built Thu Mar  6 11:50:23 PST 2003)
 */

package _xsl;

import java.io.*;
import java.util.*;
import org.w3c.dom.*;
import org.xml.sax.*;
import com.caucho.util.*;
import com.caucho.xml.*;
import com.caucho.xpath.*;
import com.caucho.xpath.expr.*;
import com.caucho.xpath.pattern.*;
import com.caucho.xsl.*;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _c_23a_25cprogramme_25cresin_25cresin_22d2__1__8_25cresin_22d2__1__8_25cwebapps_25cbookmarks_25cxml_25cbmkfolders__xsl extends JavaStylesheet {
  private StylesheetEnv stylesheets[];
  // '/'
// C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl:6  
  private void _xsl_template_(XslWriter out, Node inputNode, Env env)
    throws Exception
  {
    Object _xsl_tmp;
    Node node = inputNode;
    boolean oldEscaping = out.disableEscaping(false);
    env.setStylesheetEnv(stylesheets[0]);
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 6);
    out.pushElement("html");
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 6);
    out.pushElement("head");
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 6);
    out.pushElement("TITLE");
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 8);
    out.write(_xsl_string0, 0, 9);
    out.popElement();
    out.popElement();
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 8);
    out.pushElement("body");
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 8);
    out.pushElement("center");
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 8);
    out.pushElement("H1");
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 8);
    out.pushElement("font");
    out.pushAttribute("", "color", null);
    out.print("blue");
    out.popAttribute();
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 12);
    out.write(_xsl_string1, 0, 34);
    out.popElement();
    out.popElement();
    out.popElement();
    {
      Env _xsl_arg1 = XPath.createCall(env);
      _xsl_arg1.setSelect(node, null);
      for (Node _xsl_node = node.getFirstChild();
           _xsl_node != null;
           _xsl_node = _xsl_node.getNextSibling()) {
        _xsl_arg1.setCurrentNode(_xsl_node);
        applyNode(out, _xsl_node, _xsl_arg1, 0, 2147483647);
      }
    }
    out.popElement();
    out.popElement();
    out.disableEscaping(oldEscaping);
  }
  
  // 'rootfolder'
// C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl:19  
  private void _xsl_template_0(XslWriter out, Node inputNode, Env env)
    throws Exception
  {
    Object _xsl_tmp;
    Node node = inputNode;
    boolean oldEscaping = out.disableEscaping(false);
    env.setStylesheetEnv(stylesheets[0]);
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 19);
    out.pushElement("DL");
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 19);
    out.pushElement("p");
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 19);
    out.pushElement("DT");
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 19);
    out.pushElement("h2");
    out.pushAttribute("ADD_DATE");
    if (node instanceof Element)
      out.print(((Element) node).getAttribute("add_date"));
    out.popAttribute();
    if (node instanceof Element)
      out.print(((Element) node).getAttribute("titel"));
    out.popElement();
    out.popElement();
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 20);
    out.pushElement("DL");
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 20);
    out.pushElement("p");
    {
      Env _xsl_arg1 = XPath.createCall(env);
      _xsl_arg1.setSelect(node, _select_patterns[0]);
      for (Node _xsl_ptr0 = node.getFirstChild();
           _xsl_ptr0 != null;
           _xsl_ptr0 = _xsl_ptr0.getNextSibling()) {
        if (_xsl_ptr0.getNodeName() == "bookmarks" &&
            _xsl_ptr0 instanceof Element) {
          _xsl_arg1.setCurrentNode(_xsl_ptr0);
          applyNode(out, _xsl_ptr0, _xsl_arg1, 0, 2147483647);
        }
      }
    }
    {
      Env _xsl_arg1 = XPath.createCall(env);
      _xsl_arg1.setSelect(node, _select_patterns[1]);
      for (Node _xsl_ptr1 = node.getFirstChild();
           _xsl_ptr1 != null;
           _xsl_ptr1 = _xsl_ptr1.getNextSibling()) {
        if (_xsl_ptr1.getNodeName() == "folder" &&
            _xsl_ptr1 instanceof Element) {
          _xsl_arg1.setCurrentNode(_xsl_ptr1);
          applyNode(out, _xsl_ptr1, _xsl_arg1, 0, 2147483647);
        }
      }
    }
    out.popElement();
    out.popElement();
    out.popElement();
    out.popElement();
    out.disableEscaping(oldEscaping);
  }
  
  // 'folder'
// C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl:24  
  private void _xsl_template_1(XslWriter out, Node inputNode, Env env)
    throws Exception
  {
    Object _xsl_tmp;
    Node node = inputNode;
    boolean oldEscaping = out.disableEscaping(false);
    env.setStylesheetEnv(stylesheets[0]);
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 24);
    out.pushElement("DT");
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 24);
    out.pushElement("h3");
    out.pushAttribute("ADD_DATE");
    if (node instanceof Element)
      out.print(((Element) node).getAttribute("add_date"));
    out.popAttribute();
    if (node instanceof Element)
      out.print(((Element) node).getAttribute("titel"));
    out.popElement();
    out.popElement();
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 27);
    out.pushElement("DL");
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 27);
    out.pushElement("p");
    {
      Env _xsl_arg1 = XPath.createCall(env);
      _xsl_arg1.setSelect(node, _select_patterns[0]);
      for (Node _xsl_ptr0 = node.getFirstChild();
           _xsl_ptr0 != null;
           _xsl_ptr0 = _xsl_ptr0.getNextSibling()) {
        if (_xsl_ptr0.getNodeName() == "bookmarks" &&
            _xsl_ptr0 instanceof Element) {
          _xsl_arg1.setCurrentNode(_xsl_ptr0);
          applyNode(out, _xsl_ptr0, _xsl_arg1, 0, 2147483647);
        }
      }
    }
    {
      Env _xsl_arg1 = XPath.createCall(env);
      _xsl_arg1.setSelect(node, _select_patterns[1]);
      for (Node _xsl_ptr1 = node.getFirstChild();
           _xsl_ptr1 != null;
           _xsl_ptr1 = _xsl_ptr1.getNextSibling()) {
        if (_xsl_ptr1.getNodeName() == "folder" &&
            _xsl_ptr1 instanceof Element) {
          _xsl_arg1.setCurrentNode(_xsl_ptr1);
          applyNode(out, _xsl_ptr1, _xsl_arg1, 0, 2147483647);
        }
      }
    }
    out.popElement();
    out.popElement();
    out.disableEscaping(oldEscaping);
  }
  
  // 'bookmarks'
// C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl:30  
  private void _xsl_template_2(XslWriter out, Node inputNode, Env env)
    throws Exception
  {
    Object _xsl_tmp;
    Node node = inputNode;
    boolean oldEscaping = out.disableEscaping(false);
    env.setStylesheetEnv(stylesheets[0]);
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 30);
    out.pushElement("DT");
    out.setLocation("C:\\Programme\\RESIN\\resin-2.1.8\\resin-2.1.8\\webapps\\bookmarks\\xml\\bmkfolders.xsl", 30);
    out.pushElement("a");
    out.pushAttribute("href");
    if (node instanceof Element)
      out.print(((Element) node).getAttribute("url"));
    out.popAttribute();
    out.pushAttribute("ADD_DATE");
    if (node instanceof Element)
      out.print(((Element) node).getAttribute("add_date"));
    _xsl_loop0:
    for (Node _xsl_ptr1 = node.getFirstChild();
         _xsl_ptr1 != null;
         _xsl_ptr1 = _xsl_ptr1.getNextSibling()) {
      if (_xsl_ptr1.getNodeName() == "bookmarks" &&
          _xsl_ptr1 instanceof Element) {
        out.valueOf(_xsl_ptr1);
        break _xsl_loop0;
      }
    }
    out.popAttribute();
    out.valueOf(node);
    out.popElement();
    out.popElement();
    out.disableEscaping(oldEscaping);
  }
  
  protected void applyNode(XslWriter out, Node node, Env env, int _xsl_min, int _xsl_max)
    throws Exception
  {
    Object _xsl_tmp;
    
    switch (getTemplateId(_static_templates, node, env, _xsl_min, _xsl_max)) {
    case 1:
      _xsl_template_(out, node, env);
      break;
    case 2:
      _xsl_template_0(out, node, env);
      break;
    case 3:
      _xsl_template_1(out, node, env);
      break;
    case 4:
      _xsl_template_2(out, node, env);
      break;
    default:
      switch (node.getNodeType()) {
      case Node.ELEMENT_NODE:
      case Node.DOCUMENT_NODE:
      case Node.DOCUMENT_FRAGMENT_NODE:
        env.setSelect(node, null);
        for (Node child = node.getFirstChild();
             child != null;
             child = child.getNextSibling()) {
          env.setCurrentNode(child);
          applyNode(out, child, env, 0, 2147483647);
        }
        break;
      default:
        applyNodeDefault(out, node, env);
        break;
      }
      break;
    }
  }
  
  static HashMap _static_templates;
  
  static {
    _static_templates = new HashMap();
    Template []values;
    try {
      Template []star = new Template[] {
        new Template(XPath.parseMatch("/").getPattern(), "", 0, 0, 0.5, 0, "_xsl_template_", 1),
      };
      
      _static_templates.put("*", star);
      _init_templates_0(star);
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
  private static void _init_templates_0(Template []star)
    throws Exception
  {
    _static_templates.put("bookmarks", 
      mergeTemplates(star, new Template[] {
        new Template(XPath.parseMatch("bookmarks").getPattern(), "", 0, 0, 0.0, 3, "_xsl_template_2", 4),
    }));
    _static_templates.put("folder", 
      mergeTemplates(star, new Template[] {
        new Template(XPath.parseMatch("folder").getPattern(), "", 0, 0, 0.0, 2, "_xsl_template_1", 3),
    }));
    _static_templates.put("rootfolder", 
      mergeTemplates(star, new Template[] {
        new Template(XPath.parseMatch("rootfolder").getPattern(), "", 0, 0, 0.0, 1, "_xsl_template_0", 2),
    }));
  }
  private void _xsl_init_vars(XslWriter out, Node node, Env env)
    throws Exception
  {
    Object _xsl_tmp;
    com.caucho.vfs.Path pwd;
    pwd = (com.caucho.vfs.Path) out.getProperty("caucho.pwd");
  }
  protected void _xsl_init(XslWriter out, Node node, Env env)
    throws Exception
  {
    Object _xsl_tmp;
    _xsl_init_vars(out, node, env);
  }
  public boolean isModified()
  {
    return com.caucho.util.CauchoSystem.getVersionId() != 2057024150 ||
           super.isModified();
  }
  public void init(com.caucho.vfs.Path path)
    throws Exception
  {
    super.init(path);
    com.caucho.vfs.Path pwd = path.getParent();
    addDepend(pwd.lookup("/C:/Programme/RESIN/resin-2.1.8/resin-2.1.8/webapps/bookmarks/xml/bmkfolders.xsl"), 1049696632000L,1365L);
    stylesheets = new StylesheetEnv[1];
    StylesheetEnv env;
    env = new StylesheetEnv();
    stylesheets[0] = env;
    env.setPath(pwd.lookup("/C:/Programme/RESIN/resin-2.1.8/resin-2.1.8/webapps/bookmarks/xml/bmkfolders.xsl"));
    output.put("encoding", "ISO-8859-1");
    output.put("method", "html");
    
    com.caucho.xsl.fun.KeyFun keyFun = new com.caucho.xsl.fun.KeyFun();
    addFunction("key", keyFun);
    
    com.caucho.xsl.fun.FormatNumberFun formatFun = new com.caucho.xsl.fun.FormatNumberFun();
    java.text.DecimalFormatSymbols symbols;
    addFunction("format-number", formatFun);
  }
  static char[] _xsl_string0 = "Bookmarks".toCharArray();
  static char[] _xsl_string1 = "Meine Ordner aus dem Bookmark-Tool".toCharArray();
  private static com.caucho.xpath.pattern.AbstractPattern []_select_patterns;
  private static com.caucho.xpath.pattern.AbstractPattern []_match_patterns;
  static {
    try {
      _select_patterns = new com.caucho.xpath.pattern.AbstractPattern[] { 
        XPath.parseSelect("bookmarks").getPattern(),
        XPath.parseSelect("folder").getPattern(),
      };
      _match_patterns = new com.caucho.xpath.pattern.AbstractPattern[] { 
      };
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
